FAVORITES = [{user_id: 1,
              park_id: 79},
             {user_id: 1,
              park_id: 34},
             {user_id: 1,
              park_id: 124},
             {user_id: 1,
              park_id: 115},
             {user_id: 1,
              park_id: 65},
             {user_id: 1,
              park_id: 3},
             {user_id: 1,
              park_id: 11},]