REVIEWS = [{ user_id: 1, 
             park_id: 79,
             overall: 5,
             atmosphere: 4,
             family_friendliness: 5,
             intensity: 2,
             wait_times: 3,
             cost: 4,
             title: "Wonderful",
             body: "The whole family had a great time. Highly recommended."},
           { user_id: 2, 
             park_id: 79,
             overall: 4,
             atmosphere: 5,
             family_friendliness: 5,
             intensity: 1,
             wait_times: 2,
             cost: 3,
             title: "Good at what it does",
             body: "Offers a great experience, but not much in the way of thrills."},
           { user_id: 3, 
             park_id: 79,
             overall: 4,
             atmosphere: 5,
             family_friendliness: 4,
             intensity: 3,
             wait_times: 2,
             cost: 4,
             title: "One of my favorite parks",
             body: "If you can get past the cold weather, you'll have a great time."},
           { user_id: 4, 
             park_id: 79,
             overall: 4,
             atmosphere: 5,
             family_friendliness: 4,
             intensity: 4,
             wait_times: 3,
             cost: 4,
             title: "I love this place.",
             body: "I've been going here since I was a kid, and it's the best!"},
           { user_id: 1, 
             park_id: 34,
             overall: 3,
             atmosphere: 5,
             family_friendliness: 4,
             intensity: 3,
             wait_times: 2,
             cost: 1,
             title: "A nice place, maybe not worth the cost",
             body: "I had a pretty good time, but the price is very expensive. Not sure if I'd recommend it if price is a concern at all. There is a lot to do once you're there, though."},
           { user_id: 2, 
             park_id: 34,
             overall: 5,
             atmosphere: 4,
             family_friendliness: 5,
             intensity: 2,
             wait_times: 3,
             cost: 3,
             title: "",
             body: ""},
           { user_id: 1, 
             park_id: 79,
             overall: 5,
             atmosphere: 4,
             family_friendliness: 5,
             intensity: 2,
             wait_times: 3,
             cost: 3,
             title: "",
             body: ""},
           { user_id: 1, 
             park_id: 79,
             overall: 5,
             atmosphere: 4,
             family_friendliness: 5,
             intensity: 2,
             wait_times: 3,
             cost: 3,
             title: "",
             body: ""},
           { user_id: 1, 
             park_id: 79,
             overall: 5,
             atmosphere: 4,
             family_friendliness: 5,
             intensity: 2,
             wait_times: 3,
             cost: 3,
             title: "",
             body: ""},
           { user_id: 1, 
             park_id: 79,
             overall: 5,
             atmosphere: 4,
             family_friendliness: 5,
             intensity: 2,
             wait_times: 3,
             cost: 3,
             title: "",
             body: ""},
           { user_id: 1, 
             park_id: 79,
             overall: 5,
             atmosphere: 4,
             family_friendliness: 5,
             intensity: 2,
             wait_times: 3,
             cost: 3,
             title: "",
             body: ""},
           { user_id: 1, 
             park_id: 79,
             overall: 5,
             atmosphere: 4,
             family_friendliness: 5,
             intensity: 2,
             wait_times: 3,
             cost: 3,
             title: "",
             body: ""},
           { user_id: 1, 
             park_id: 79,
             overall: 5,
             atmosphere: 4,
             family_friendliness: 5,
             intensity: 2,
             wait_times: 3,
             cost: 3,
             title: "",
             body: ""},]