USERS = [{ email: "guest@themeparklist.info",
           username: "Guest",
           password: "guestguest" },
         { email: "joe@email.com",
           username: "Joe",
           password: "joejoe" },
         { email: "bob@email.com",
           username: "Bob",
           password: "bobbob" },
         { email: "jane@email.com",
           username: "Jane",
           password: "janejane" }]