# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# { name: ,
# latitude: ,
# longitude: ,
# city: ,
# state: ,
# country: ,
# opening_date: ,
# closing_date: ,
# image_url: ,
# tripadv_rating: ,
# rides: ,
# roller_coasters: ,
# water_rides: }

PARKS = [{ name: "Six Flags Magic Mountain",
           latitude: 34.42,
           longitude: -118.59,
           city: "Los Angeles",
           state: "California",
           country: "United States",
           image_url: "magic_mountain.jpg",
           tripadv_rating: 86,
           rides: 44,
           roller_coasters: 19,
           water_rides: 3 },
         { name: "California's Great America",
           latitude: 37.23,
           longitude: 121.58,
           city: "Santa Clara",
           state: "California",
           country: "United States",
           image_url: "californias_great_america.jpg",
           tripadv_rating: 76,
           rides: 58,
           roller_coasters: 8,
           water_rides: 3 },
         { name: "Waterville USA",
            url: "http://watervilleusa.com/",
            latitude: 30.15,
            longitude: 87.41,
            city: "906 Gulf Shores Pkwy Gulf Shores",
            state: "Alabama",
            country: "U.S.",
            image_url: "waterville_usa.jpg",
            rides: 19,
            roller_coasters: 1,
            water_rides: 12 },
          { name: "Magic Springs and Crystal Falls",
            url: "http://www.magicsprings.com",
            latitude: 34.31,
            longitude: 93.0,
            city: "Hot Springs",
            state: "Arkansas",
            country: "United States",
            image_url: "magic_springs.jpg",
            rides: 20,
            roller_coasters: 5,
            water_rides: 2 },
          { name: "Santa Cruz Beach Boardwalk",
            url: "http://www.beachboardwalk.com",
            latitude: 36.57,
            longitude: 122.01,
            city: "Santa Cruz",
            state: "California",
            country: "United States",
            image_url: "beach_boardwalk.jpg",
            rides: 35,
            roller_coasters: 3,
            water_rides: 1 },
          { name: "Pacific Park",
            url: "http://www.pacpark.com/",
            latitude: 34.0,
            longitude: 118.29,
            city: "Santa Monica",
            state: "California",
            country: "United States",
            image_url: "pacific_park.jpg",
            rides: 12,
            roller_coasters: 1,
            water_rides: "null"},] 

PARKS.each { |park| Park.create(park) }

USERS = [{ email: "joe@gmail.com",
           password: "joejoe" },
         { email: "bob@yahoo.com",
           password: "bobbob" }]

USERS.each { |user| User.create(user) }